-- 1. INSERT CATEGORIES
INSERT INTO products_category (id, name, description, is_active) VALUES 
(6, 'Agriculture', 'Farming supplies, equipment and nursery', true),
(9, 'Automobile', 'New vehicles - two, four wheelers and commercial', true),
(11, 'Construction', 'Hardware, paint, electrical and fabrication', true),
(4, 'Electronics', 'Mobile, Laptops, and Home Appliances', true),
(13, 'Event Management', 'Stage decoration, catering and photography', true),
(2, 'Fashion', 'Textiles, Shoes, and Fashion Accessories', true),
(12, 'Furnitures', 'Home and office furniture', true),
(7, 'Mart', 'Supermarkets, wholesale and convenience stores', true),
(10, 'Second Hand Vehicles', 'Pre-owned two, four wheelers and heavy vehicles', true),
(8, 'Traders', 'Livestock and commodity traders', true);

-- 2. INSERT SUBCATEGORIES
INSERT INTO products_subcategory (id, category_id, name) VALUES 
(38, 6, 'Agri Equipments'),
(39, 6, 'Feeds & Cattle Feeds'),
(40, 6, 'Fertilizers & Pesticides'),
(41, 6, 'Nursery'),
(42, 6, 'Seeds'),
(43, 2, 'Textile'),
(44, 2, 'Shoes'),
(45, 2, 'Tailors'),
(46, 2, 'Rental Stores'),
(47, 2, 'Beautician'),
(48, 2, 'Saree & Fancy Printing'),
(49, 7, 'Supermarkets'),
(50, 7, 'Convenience Stores'),
(51, 7, 'Wholesale Markets'),
(52, 7, 'General Stores'),
(53, 4, 'Mobile'),
(54, 4, 'Laptop'),
(55, 4, 'Home Appliances'),
(56, 4, 'Audio & Video'),
(57, 4, 'Accessories'),
(58, 8, 'Cow'),
(59, 8, 'Sheep'),
(60, 8, 'Silage'),
(61, 8, 'Goats'),
(62, 8, 'Pets'),
(63, 8, 'Coffee Traders'),
(64, 9, 'Two Wheelers'),
(65, 9, 'Four Wheelers'),
(66, 9, 'Commercial'),
(67, 9, 'Modified Vehicles'),
(68, 10, 'Two Wheeled'),
(69, 10, 'Four Wheeled'),
(70, 10, 'Commercial Vehicles'),
(71, 10, 'Heavy Vehicles'),
(72, 11, 'Hardware'),
(73, 11, 'Paints'),
(74, 11, 'Electric Items'),
(75, 11, 'Tiles & Granite'),
(76, 11, 'Carpentry & Wood'),
(77, 11, 'PVC Fabrication'),
(78, 11, 'Others'),
(79, 12, 'Sofas'),
(80, 12, 'Beds'),
(81, 12, 'Dining'),
(82, 12, 'Office Furniture'),
(83, 12, 'Outdoor Furniture'),
(84, 13, 'Stage Decoration'),
(85, 13, 'Catering'),
(86, 13, 'Photography Studio');
