# Generated by Django 4.2 on 2026-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
