# Generated by Django 4.2 on 2026-06-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allow_blank_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Sub-categories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
