# Generated by Django 5.2.17 on 2026-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST percentage (e.g. 18.00)', max_digits=5),
        ),
    ]
