# Generated by Django 5.2.12 on 2026-03-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='seller',
            field=models.OneToOneField(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='users.user'),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['city'], name='shops_shop_city_0942b1_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['verification_status'], name='shops_shop_verific_d4e33c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopreview',
            unique_together={('shop', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='shopservice',
            unique_together={('shop', 'name')},
        ),
    ]
