# Generated by Django 4.2 on 2026-04-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='online_delivery_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
