# Generated by Django 4.2 on 2026-06-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_subcategory_options_subcategory_order'),
        ('shops', '0004_shop_is_open_shop_online_delivery_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='products.category'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='products.subcategory'),
        ),
    ]
