# Generated by Django 5.2.17 on 2026-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_category_shop_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
