# Generated by Django 5.2.15 on 2026-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='email',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
