# Generated by Django 5.2.15 on 2026-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_otpverification_email_otpverification_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
