# Generated by Django 5.2.15 on 2026-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_otpverification_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
